language: python
dist: bionic

python:
  - 3.8

services:
  - postgresql

addons:
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTULENV=1

install:
  - pip install pipenv
  - pipenv sync -d
  - cp contrib/env-sample .env

script:
  - pipenv run flake8 .
  - pipenv run pytest --cov=pypro

before_install:
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.3,12}/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres

after_success:
  - pipenv run codecov
